name: xsys keep

on:
  workflow_dispatch: # 允许在 Actions 页面手动触发
  schedule:
    - cron: '26 2 */2 * *'

jobs:
  add_time:
    runs-on: ubuntu-latest 

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/renew_tasks
          token: ${{ secrets.GH_TOKEN }}

